export const CONFIG = {
  canvas: { width: 960, height: 540 },
  world: { groundY: 430, gravity: 2200, maxFallSpeed: 1450 },
  player: {
    width: 34,
    height: 46,
    startX: 110,
    startY: 384,
    baseSpeed: 215,
    speedStepPerFiveLaps: 6,
    smallJumpVelocity: -640,
    bigJumpVelocity: -840,
    invincibleMs: 1150,
    knockbackSpeed: 150,
  },
  input: {
    bigPressMs: 260,
  },
  obstacles: {
    lowWallHeight: 54,
    highWallHeight: 104,
    wallWidth: 36,
    pitMinWidth: 74,
    pitMaxWidth: 136,
    minGap: 58,
    safeStartZone: 180,
  },
  difficulty: {
    startDensity: 0.24,
    maxDensity: 0.62,
    startHighWallRate: 0.18,
    startChainRate: 0.1,
    startPitRate: 0.2,
    enemyBaseCap: 6,
    enemyMaxCap: 15,
  },
  terrain: {
    useBrakeV2: true,
    useMotifGenerator: true,
    enablePlatforms: true,
    baseDangerBudget: 9.8,
    dangerBudgetPerLap: 0.28,
    dangerBudgetVariance: 1.1,
    maxSameMotifStreak: 2,
    restZoneMinPerLap: 1,
    motifWeights: {
      flatRun: 0.95,
      chain: 1.0,
      pitZone: 0.9,
      restZone: 0.56,
      platformZone: 0.82,
    },
    platformRate: 0.16,
    platformChainRate: 0.46,
    platformHeightBandMin: 110,
    platformHeightBandMax: 170,
    platformWidthMin: 42,
    platformWidthMax: 84,
    platformGapMin: 34,
    platformGapMax: 78,
    platformCost: 0.85,
    introSimpleLaps: 1,
    highWallSpawnScale: 1.45,
    wallGapTightMaxPx: 17,
    wallGapOpenMinPx: 68,
  },
  debug: {
    showTerrainOverlay: false,
    logTerrainReason: false,
  },
  enemies: {
    radius: 13,
    mergeProgressGap: 0.045,
    despawnX: -70,
    spawnAheadX: 82,
    maxSpawnPerFrame: 1,
    baseActiveCap: 3,
    capGrowthEveryLap: 3,
    rightEdgeNoHitWidth: 84,
    leftEdgeNoHitWidth: 42,
    leftEdgeSafeMs: 130,
    speedGrowthPerLap: 1.4,
    speedByKind: {
      sineLow: 178,
      sineHigh: 192,
      hover: 168,
      runner: 206,
    },
  },
  scoring: {
    survivalPerSecond: 10,
    lapBonus: 400,
    dodgeBonus: 70,
  },
  storage: {
    bestScoreKey: "echoLoopBestScore",
  },
};

export const STORAGE_KEYS = {
  best: CONFIG.storage.bestScoreKey,
  bgmVolumeLevel: "echoLoopBgmVolumeLevel",
  sfxVolumeLevel: "echoLoopSfxVolumeLevel",
  bgmVariant: "echoLoopBgmVariant",
  legacyBgmEnabled: "echoLoopBgmEnabled",
  legacySfxEnabled: "echoLoopSfxEnabled",
};

export const TYPE_PRIORITY = { smallJump: 1, bigJump: 2, brake: 3 };

